version: "3"

services:
  count_together_backend:
    image: aymericbernard/count-together-backend:latest
    container_name: count_together_backend
    restart: always
    environment:
      - VIRTUAL_HOST=count-together-backend.example.com
      - LETSENCRYPT_HOST=count-together-backend.example.com
      - LETSENCRYPT_EMAIL=example@example.com
      - MONGO_HOST=count_together_mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=counttogetherpasswordroot
    depends_on:
      - count_together_mongo
    networks:
      - count_together_internal
      - proxy

  count_together_mongo:
    image: mongo:4.4.10
    container_name: count_together_mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=count
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=counttogetherpasswordroot
    volumes:
      - /home/bebert/count_together_mongo_db:/data/db
    networks:
      - count_together_internal

networks:
  proxy:
    external:
      name: nginx-proxy
  count_together_internal:
